version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend
